# Generated by Django 5.2.11 on 2026-03-07 00:11

import django.db.models.deletion
import recipes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/', validators=[recipes.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='steps/', validators=[recipes.models.validate_image_size]),
        ),
    ]
