# Generated by Django 5.2.11 on 2026-03-07 00:21

from django.conf import settings
from django.db import migrations


def create_profiles(apps, schema_editor):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    UserProfile = apps.get_model('recipes', 'UserProfile')
    for user in User.objects.all():
        UserProfile.objects.get_or_create(user=user, defaults={'is_approved': True})


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_userprofile'),
    ]

    operations = [
        migrations.RunPython(create_profiles, migrations.RunPython.noop),
    ]
